### ISSUE TITLE
字符显示异常

### ISSUE THREAD

**Issue by GeekFanxyhere** [BetterNCM/CppLyrics#2]
![image](https://github.com/BetterNCM/CppLyrics/assets/144511273/99e7407d-67d6-40de-9e01-baa62f8ebd8a)
![image](https://github.com/BetterNCM/CppLyrics/assets/144511273/d2368154-b411-484f-bb91-a3aae06c34bd)
对除英文、数字外无法显示任何字符，会变成方块占位符，安装常用的字体无济于事，其他项目可正常运行并使用常见语言

**Comment by std-microblock** [comment]
该项目仍在早期阶段 所以先写死了 [Noto Sans SC](https://fonts.google.com/noto/specimen/Noto+Sans+SC)
